# Site settings
title: Christian Gabbani @ Fabacademy 2015
email: christian.gabbani@gmail.com
description: This site is the diary of an adventure on the path of "How to build almost anything".
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://githubgeo.github.io" # the base hostname & protocol for your site
twitter_username: geo_oeg
github_username:  GithubGeo

# Build settings
markdown: kramdown
